### ISSUE TITLE
Question - The music player in screenshots

### ISSUE THREAD

**Issue by awwRoar** [acszo/Redomi#16]
Hey, consider me silly, I just wanted to know which music player (app) is used here for the repo screenshots here. It looks beautiful. Kindly let me know and excuse me for opening an issue for something so trivial 🥹

Thank you

**Comment by acszo** [comment]
Hi, sure don't worry about it, on the screenshots I've been using [InnerTune](https://github.com/z-huang/InnerTune), meanwhile for the gifs [ViMusic](https://github.com/vfsfitvnm/ViMusic), but there's also a fork of it that gets updates called [ViTune](https://github.com/25huizengek1/ViTune), they're all 3rd party clients for YT Music. Maybe I should state them on the readme

**Comment by awwRoar** [comment]
Great. I missed this reply somehow. Thank you 😊
