### ISSUE TITLE
Yandex music support

### ISSUE THREAD

**Issue by alextrik67** [acszo/Redomi#19]
### Feature description

Adding a new service vk music.

### Why do you want it?

Link coverage will increase

**Comment by acszo** [comment]
it doesn't seem like vk music is supported by song.link, these are all the platforms it supports: https://linktree.notion.site/Supported-Platforms-e00a437c10de43fb9a6364505e9539e9

**Comment by alextrik67** [comment]
> it doesn't seem like vk music is supported by song.link, these are all the platforms it supports: https://linktree.notion.site/Supported-Platforms-e00a437c10de43fb9a6364505e9539e9
 
Since this is the case, introduce support for the Yandex service (there is support in the API), well, if you can, of course.

**Comment by acszo** [comment]
Am not familiar with Yandex music, and it seems that it's only available in some countries (not in mine). I'll ask you for a lil help. With 1.3.0 I added that if a result isn't found it will redirect you inside the app/browser with the search result pre-filled with the name of song and artist. (for example: https://www.youtube.com/results?search_query=linkin+park+one+step+closer)
Can I ask you if you can find and send me the url for it for Yandex, and see if the app correctly opens the link like the youtube one does? Thanks

**Comment by alextrik67** [comment]
> Am not familiar with Yandex music, and it seems that it's only available in some countries (not in mine). I'll ask you for a lil help. With 1.3.0 I added that if a result isn't found it will redirect you inside the app/browser with the search result pre-filled with the name of song and artist. (for example: https://www.youtube.com/results?search_query=linkin+park+one+step+closer) Can I ask you if you can find and send me the url for it for Yandex, and see if the app correctly opens the link like the youtube one does? Thanks

Here's the link: https://music.yandex.ru/album/18111/track/178493

**Comment by acszo** [comment]
Sorry, I meant the search query not the actual link to the song. I'll show you the difference

1 - This is the search link for yt, which puts the song and artist names into the search bar:
https://www.youtube.com/results?search_query=linkin+park+one+step+closer

2 - And this is the actual song on yt:
https://www.youtube.com/watch?v=4qlCC1GOwFw

I need the first one, but for yandex music, to see if the app works the same way as youtube

**Comment by onemonday** [comment]
Hello everyone!

Here's the link with search query:
https://music.yandex.ru/search?text=linkin%20park%20one%20step%20closer

**Comment by acszo** [comment]
Thank you 🙏
