### ISSUE TITLE
Revanced... ✨

### ISSUE THREAD

**Issue by Zan1456** [acszo/Redomi#2]
### Feature description

Option to enter the name of the application package (in an advanced settigs menu or idk)

### Why do you want it?

The application does not recognize the app modded with revanced because the package name has changed.

**Comment by acszo** [comment]
Did you change the package names yourself from revanced or they really changed them? Haven't noticed on my end

**Comment by Zan1456** [comment]
I use pre-built ones. (app.rvx.android.apps.youtube.music)

**Comment by acszo** [comment]
that's from revanced extended, i forgot it was a thing. I just added them manually. I'll take in consideration your suggestion, and see if to implement it or change some stuff to not chase apps 🫡

**Comment by acszo** [comment]
Check out 1.1.0, i made some changes, now it doesn't look for installed apps, and shows everything by default, but it will work with anything. Only downside is that you will have to uncheck more apps

**Comment by Zan1456** [comment]
Thank you for doing it. 💕
