### ISSUE TITLE
Add support for Spotube app

### ISSUE THREAD

**Issue by ItzxDwi** [acszo/Redomi#24]
### Feature description

add support for the app of Spotube

### Why do you want it?

because Spotube doesn't contains ads

### Additional context

💫🐢

**Comment by acszo** [comment]
Redomi works with 3rd party clients, just make sure spotube can open spotify links and it will work
<img width="302" alt="spotube" src="https://github.com/user-attachments/assets/64260f70-cdec-4d8a-ad92-50620c6d40e6">

**Comment by ItzxDwi** [comment]
> Redomi works with 3rd party clients, just make sure spotube can open spotify links and it will work <img alt="spotube" width="302" src="https://private-user-images.gi">

**Comment by ItzxDwi** [comment]
> Redomi works with 3rd party clients, just make sure spotube can open spotify links and it will work <img alt="spotube" width="302" src="https://private-user-images.gi">

**Comment by ItzxDwi** [comment]
alr thanks
