### ISSUE TITLE
Add support for Anghami

### ISSUE THREAD

**Issue by bobarakatx** [acszo/Redomi#27]
### Feature description

Anghami is another music app that's popular in the MENA region. I use Spotify but alot of my friends use Anghami.
The app can already convert Anghami links that I get to Spotify if I share the link to it, but it does not have the ability to convert Spotify links to Anghami.

### Why do you want it?

Add support for the Anghami music streaming app.

**Comment by acszo** [comment]
Yes, song.link does support Anghami, I'll add support for it 🫡
